### ISSUE TITLE
Do not install.

### ISSUE THREAD

**Issue by alexb3d** [flathub/org.jdownloader.JDownloader#25]
A few days ago I got errors when updating the plugins, I deleted the folder in .var and when doing a new installation I get this:

org.tukaani.xz.CorruptedInputException: XZ Index is corrupt
	at org.tukaani.xz.index.IndexHash.validate(Unknown Source)
	at org.tukaani.xz.SingleXZInputStream.read(Unknown Source)
	at org.tukaani.xz.XZInputStream.read(Unknown Source)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:132)
	at org.appwork.utils.net.CountingInputStream.read(CountingInputStream.java:62)
	at org.appwork.utils.net.LimitedInputStream.read(LimitedInputStream.java:70)
	at org.appwork.utils.awfc.AWFCInputStream$2.read(AWFCInputStream.java:144)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:106)
	at org.appwork.utils.awfc.AWFCInputStream.read(AWFCInputStream.java:212)
	at org.appwork.updatesys.client.UpdateClient$15$1.read(UpdateClient.java:3113)
	at org.appwork.utils.crypto.AWSign.verify(AWSign.java:453)
	at org.appwork.updatesys.transport.exchange.UpdateSignature.verify(UpdateSignature.java:163)
	at org.appwork.updatesys.client.UpdateClient.verifyFileSignature(UpdateClient.java:3140)
	at org.appwork.updatesys.client.UpdateClient.writeFile(UpdateClient.java:3169)
	at org.appwork.updatesys.client.UpdateClient.installFile(UpdateClient.java:3223)
	at org.jdownloader.update.SelfUpdateClient.installFile(SelfUpdateClient.java:198)
	at org.appwork.updatesys.client.UpdateClient.installPackage(UpdateClient.java:3468)
	at org.appwork.updatesys.client.UpdateClient.runPackageInstallation(UpdateClient.java:4768)
	at org.jdownloader.update.SelfUpdateClient.runPackageInstallation(SelfUpdateClient.java:531)
	at org.jdownloader.update.UpdateManager.runUpdateLoop(UpdateManager.java:1343)
	at org.jdownloader.update.PendingUpdate.run(PendingUpdate.java:19)
	at org.jdownloader.update.UpdateManager$23.run(UpdateManager.java:1692)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by KuSh** [comment]
Seems to be a temporary problem in view of the daily installs/updates

**Comment by alexb3d** [comment]
I have no idea, I installed the native version.
